#
# Time-stamp: <2016-06-18 15:23:52 alex>

---
- name: INSTALL PROBE
  hosts: piprobes
  remote_user: pi
  become_user: root

  tasks:
   - name: update apt
     become: true
     apt: update_cache=yes

   - name: install apt https transport
     become: true
     apt: name=apt-transport-https update_cache=yes cache_valid_time=3600

   - name: install git
     become: true
     apt: name=git update_cache=yes cache_valid_time=3600

   - name: install pip
     become: true
     apt: name=python-pip update_cache=yes cache_valid_time=3600

   - name: get python path
     command: python -c "import sys; print sys.path[1]"
     register: pythonpath

   - name: clean old impacket git
     file: path=/tmp/imp
           state=absent
     become: true

   - name: create directory for imp
     file: path=/tmp/imp state=directory mode=0755

   - name: install git impacket
     git: repo=https://github.com/CoreSecurity/impacket
          dest=/tmp/imp

   - name: clean old impacket
     file: path={{ pythonpath.stdout }}/impacket
           state=absent
     become: true

   - name: install impacket
     command: mv /tmp/imp/impacket {{ pythonpath.stdout }}
     become: true

   - name: install redis package
     become: true
     apt: name=redis-server update_cache=yes cache_valid_time=3600

   - name: install python-dev package
     become: true
     apt: name=python-dev update_cache=yes cache_valid_time=3600

   - name: install python requests
     become: true
     pip: name=requests

   - name: install python netifaces
     become: true
     pip: name=netifaces

   - name: install python redis
     become: true
     pip: name=redis

   - name: redis save 1/3
     become: true
     lineinfile: dest=/etc/redis/redis.conf regexp='^(save 900 1)$' line='#\1' backrefs=yes

   - name: redis save 2/3
     become: true
     lineinfile: dest=/etc/redis/redis.conf regexp='^(save 300 10)$' line='#\1' backrefs=yes

   - name: redis save 3/3
     become: true
     lineinfile: dest=/etc/redis/redis.conf regexp='^(save 60 10000)$' line='#\1' backrefs=yes

   - name: redis log
     become: true
     lineinfile: dest=/etc/redis/redis.conf regexp=^logfile line="logfile /dev/null"

   - name: install python psutil
     become: true
     pip: name=psutil

   - name: copy sources
     unarchive: src=../files/netprobe.tgz dest=/home/pi

   - name: probe at boot
     become: true
     lineinfile: dest=/etc/rc.local line="/home/pi/py-net-probe/start.sh &" state=present insertbefore="^exit 0"
