#
# install pi from scratch (raspbian lite)
#
# Time-stamp: <2017-01-29 14:06:39 alex>
#
#
# usage :
#  ssh direct in order to add the hash in the known_hosts
#  ansible-playbook -i files/hosts playbooks/pi-all.yml --ask-pass
#   --limit %IP%
#
# --------------------------------------------------------------------
# PiProbe
# Copyright (C) 2016-2017  Alexandre Chauvin Hameau <ach@meta-x.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later 
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# --------------------------------------------------------------------

---
- name: PI PROBE
  hosts: new
  become: true
  become_user: root
  remote_user: pi

  tasks:
#    - include : pi-init-init.yml
#    - include : pi-init-upgrade.yml
#    - include : install-probe.yml
#    - include : pi-expandfs.yml

    - include : pi-ro.yml
