#
# expand the FS at first boot
#
# Time-stamp: <2017-01-29 14:06:42 alex>
#
#
# --------------------------------------------------------------------
# PiProbe
# Copyright (C) 2016-2017  Alexandre Chauvin Hameau <ach@meta-x.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later 
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# --------------------------------------------------------------------

   - name: install rc-expandfs
     become: true
     copy: src=../files/rc-expandfs dest=/etc owner=root group=root mode=0744

   - name: install rc-expandpart
     become: true
     copy: src=../files/rc-expandpart dest=/etc owner=root group=root mode=0744

   - name: exec rc in rc.local script
     become: true
     lineinfile: dest=/etc/rc.local line="/home/pi/py-net-probe/start.sh &" state=present insertbefore="^exit 0"

   - name: exec rc in rc.local script
     become: true
     blockinfile:
       dest: /etc/rc.local
       marker: "# {mark} EXPAND FS after install -->"
       insertafter: "# By default this script does nothing"
       block: |
          if [ -x /etc/rc-expandpart ]; then
             /etc/rc-expandpart
          fi
          if [ -x /etc/rc-expandfs ]; then
             /etc/rc-expandfs
          fi
