#
# initialize a raspberry pi from a raspbian lite image
#
# Time-stamp: <2016-12-11 14:52:13 alex>
#
#
# usage :
#  ansible-playbook -i files/hosts playbooks/pi-init.yml --limit %IP%
#   --ask-pass: first use
#   --tags "upgrade": for OS upgrade

   - name: set variables
     set_fact:
       ssh_key: "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"

   - name: add ssh key
     authorized_key:
       user: pi
       key: "{{ lookup('file', ssh_key) }}"
       key_options: 'no-port-forwarding'

   - name: interfaces suppress wi-fi 1/3
     become: true
     lineinfile: dest=/etc/network/interfaces regexp='^(allow-hotplug wlan.*)$' state=absent

   - name: interfaces suppress wi-fi 2/3
     become: true
     lineinfile: dest=/etc/network/interfaces regexp='^(iface wlan. inet manual)$' state=absent

   - name: interfaces suppress wi-fi 3/3
     become: true
     lineinfile: dest=/etc/network/interfaces regexp='^(.*wpa-conf .*)$' state=absent

   - name: disable audio
     become: true
     lineinfile: dest=/boot/config.txt regexp='^dtparam=audio=on' line='dtparam=audio=off' backrefs=yes

   - name: minimize gpu memory
     become: true
     lineinfile: dest=/boot/config.txt line="gpu_mem=16" state=present

   - name: turn off display
     become: true
     lineinfile: dest=/etc/rc.local line="vcgencmd display_power 0" state=present insertbefore="^exit 0"
