#
# initialize a raspberry pi from a raspbian lite image
#
# Time-stamp: <2017-01-29 14:06:53 alex>
#
#
# usage :
#  ansible-playbook -i files/hosts playbooks/pi-init.yml --limit %IP%
#   --ask-pass: first use
#   --tags "upgrade": for OS upgrade
# --------------------------------------------------------------------
# PiProbe
# Copyright (C) 2016-2017  Alexandre Chauvin Hameau <ach@meta-x.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later 
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# --------------------------------------------------------------------

---
- name: PI INIT
  hosts: new
  tags: init
  become: true
  become_user: root
  remote_user: pi

  tasks:
   - include : pi-init-init.yml

- name: PI UPGRADE
  hosts: new
  tags: upgrade
  become: true
  become_user: root
  remote_user: pi

  tasks:
    - include : pi-init-upgrade.yml
