#
# initialize a raspberry pi from a raspbian lite image
#
# Time-stamp: <2016-10-23 16:57:48 alex>
#
#
# usage :
#  ansible-playbook -i files/hosts playbooks/pi-init.yml --limit %IP%
#   --ask-pass: first use
#   --tags "upgrade": for OS upgrade

---
- name: PI INIT
  hosts: new
  tags: init
  become: true
  become_user: root
  remote_user: pi

  tasks:
   - include : pi-init-init.yml

- name: PI UPGRADE
  hosts: new
  tags: upgrade
  become: true
  become_user: root
  remote_user: pi

  tasks:
    - include : pi-init-upgrade.yml
