#
# initialize a raspberry pi from a raspbian lite image
#
# Time-stamp: <2016-05-29 15:53:17 alex>
#
#
# usage :
#  ansible-playbook -i files/hosts playbooks/pi-init.yml --limit %IP%
#   --ask-pass: first use
#   --tags "upgrade": for OS upgrade

---
- name: PI INIT
  hosts: piprobes
  tags: init
  become: true
  become_user: root
  remote_user: pi

  tasks:
   - name: set variables
     set_fact:
       ssh_key: "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"

   - name: add ssh key
     authorized_key:
       user: pi
       key: "{{ lookup('file', ssh_key) }}"
       key_options: 'no-port-forwarding'

- name: PI UPGRADE
  hosts: piprobes
  tags: upgrade
  become: true
  become_user: root
  remote_user: pi

  tasks:
   - name: update
     apt: update_cache=yes cache_valid_time=3600

   - name: suppress bluetooth
     apt: name=bluez update_cache=yes state=absent

   - name: upgrade
     apt: upgrade=yes cache_valid_time=3600
