---
- hosts: piprobes

  become: true
  become_user: root
  remote_user: pi

  tasks:
   - name: update
     apt: update_cache=yes cache_valid_time=3600

   - name: upgrade
     apt: upgrade=yes cache_valid_time=3600
